begin;
do $$declare a uuid:=gen_random_uuid();p uuid:=gen_random_uuid();c uuid:=gen_random_uuid();pr uuid:=gen_random_uuid();m uuid:=gen_random_uuid();n int;
 pepsi uuid;coke uuid;crown uuid;plastic uuid;
begin
 insert into auth.users(id,email) values(a,'a@t'),(p,'p@t'),(c,'c@t'),(pr,'pr@t'),(m,'m@t');
 update profiles set role='admin',active=true where id=a; update profiles set role='customer',active=true where id in(p,c);
 update profiles set role='production',active=true where id=pr; update profiles set role='qa_qc_manager',active=true where id=m;
 select id into pepsi from customers where name='Pepsi';select id into coke from customers where name='Coca-Cola';
 select id into crown from departments where code='CROWN';select id into plastic from departments where code='PLASTIC';
 insert into customer_users(user_id,customer_id) values(p,pepsi),(c,coke);
 insert into customer_department_access(customer_id,department_id) values(pepsi,crown),(coke,plastic);
 assert (select count(*) from departments)=3,'3 departments'; assert (select count(*) from customers)=7,'7 customers';
 assert not exists(select 1 from departments where name ilike '%liner%'),'no liner';
 perform set_config('request.jwt.claim.sub',p::text,true);set local role authenticated;
 assert (select count(*) from customers)=1 and (select name from customers)='Pepsi','pepsi sees only Pepsi';
 assert (select count(*) from customers where id=coke)=0,'pepsi cannot read Coca-Cola by id';
 assert (select count(*) from departments)=1 and (select code from departments)='CROWN','pepsi sees only CROWN';
 assert (select count(*) from customer_department_access)=1,'own access only';
 assert (select count(*) from customer_users)=1,'own mapping only';
 assert (select count(*) from profiles)=1,'own profile only';
 assert (select count(*) from audit_logs)=0,'no audit read';
 begin update profiles set role='admin' where id=p;assert false,'escalation allowed';exception when others then assert sqlerrm like 'access denied%','escalation blocked: '||sqlerrm;end;
 update customers set name='X' where id=coke;get diagnostics n=row_count;assert n=0,'pepsi edited customer';
 begin insert into customer_users(user_id,customer_id) values(p,coke);assert false,'self-link allowed';exception when insufficient_privilege then null;end;
 begin insert into audit_logs(action) values('x');assert false,'audit insert allowed';exception when insufficient_privilege then null;end;
 reset role;
 perform set_config('request.jwt.claim.sub',pr::text,true);set local role authenticated;
 assert (select count(*) from customers)=0 and (select count(*) from departments)=0,'production sees no master data';reset role;
 perform set_config('request.jwt.claim.sub',m::text,true);set local role authenticated;
 assert (select count(*) from customers)=7,'manager reads customers';
 update customers set name='Z' where id=pepsi;get diagnostics n=row_count;assert n=0,'manager cannot edit';reset role;
 perform set_config('request.jwt.claim.sub',a::text,true);set local role authenticated;
 update profiles set role='qc_checker' where id=pr;assert exists(select 1 from audit_logs where action='role_changed'),'role change audited';
 reset role;
 raise notice 'PHASE 1 RLS TESTS PASSED';
end$$;
rollback;
