begin;
do $$declare s uuid:=gen_random_uuid();cu uuid:=gen_random_uuid();pr uuid:=gen_random_uuid();mid uuid;n int;st machine_status;pb uuid;
begin
 insert into auth.users(id,email) values(s,'s@t'),(cu,'c@t'),(pr,'p@t');
 update profiles set role='qc_assistant',active=true where id=s;update profiles set role='customer',active=true where id=cu;update profiles set role='production',active=true where id=pr;
 assert (select count(*) from departments)=3,'still 3 departments';assert (select count(*) from machines)=27,'27 machines';
 assert (select count(*) from machines m join departments d on d.id=m.department_id where d.code='INJECTION_MOULDING' and m.process_id is not null)=0,'IMM separate, no process';
 assert not exists(select 1 from machines where name ilike '%liner%') and not exists(select 1 from processes where name ilike '%liner%'),'no liner';
 assert (select count(*) from qc_updates)=0 and (select count(*) from machine_current_status)=0,'no fake data';
 select id into mid from machines where name='CCM 07';
 perform set_config('request.jwt.claim.sub',s::text,true);set local role authenticated;
 insert into qc_updates(machine_id,status,remark,posted_by,created_at) values(mid,'STOPPED','Air problem',cu,'2000-01-01');
 select posted_by into pb from qc_updates;assert pb=s,'posted_by forced to caller';assert (select created_at from qc_updates)>now()-interval '1 minute','created_at forced';
 assert (select status from machine_current_status where machine_id=mid)='STOPPED','current = STOPPED';
 insert into qc_updates(machine_id,status,remark) values(mid,'RUNNING','Air problem resolved');
 assert (select status from machine_current_status where machine_id=mid)='RUNNING','latest becomes current';assert (select count(*) from qc_updates)=2,'history kept';
 begin insert into qc_updates(machine_id,status,remark) values(mid,'RUNNING','  ');assert false,'blank remark';exception when check_violation then null;end;
 begin update qc_updates set remark='x';get diagnostics n=row_count;assert n=0,'edit';exception when insufficient_privilege then null;end;
 begin delete from qc_updates;assert false,'delete';exception when insufficient_privilege then null;end;
 begin insert into machine_current_status(machine_id,status) values(mid,'HOLD');assert false,'direct status write';exception when insufficient_privilege then null;end;
 reset role;
 perform set_config('request.jwt.claim.sub',cu::text,true);set local role authenticated;
 assert (select count(*) from machines)=0 and (select count(*) from qc_updates)=0 and (select count(*) from machine_current_status)=0 and (select count(*) from processes)=0,'customer sees no internal data';
 begin insert into qc_updates(machine_id,status,remark) values(mid,'RUNNING','x');assert false,'customer post';exception when others then assert sqlerrm not like 'customer post','customer blocked';end;reset role;
 perform set_config('request.jwt.claim.sub',pr::text,true);set local role authenticated;
 assert (select count(*) from machines)=0 and (select count(*) from qc_updates)=0,'production sees nothing';
 begin insert into qc_updates(machine_id,status,remark) values(mid,'RUNNING','x');assert false,'production post';exception when others then assert sqlerrm not like 'production post','production blocked';end;reset role;
 raise notice 'PHASE 2 TESTS PASSED';
end$$;
rollback;
