import {describe,it,expect} from 'vitest';import {transitionOk,nextStatuses,editScope,isoOffset,emptyReportsMessage,canCreate,ILABEL,Rep} from '../workflow';
const R=(status:any):Rep=>({status,qc_assistant_id:'a1',qc_checker_id:'c1',qa_manager_id:'m1',created_by:'a1'});
const A={role:'qc_assistant',uid:'a1'},C={role:'qc_checker',uid:'c1'},M={role:'qa_qc_manager',uid:'m1'};
describe('workflow',()=>{
 it('assistant submits own draft only',()=>{expect(transitionOk(A,R('DRAFT'),'INSPECTION_PENDING')).toBe(true);expect(transitionOk({...A,uid:'a2'},R('DRAFT'),'INSPECTION_PENDING')).toBe(false);expect(transitionOk(A,R('INSPECTION_PENDING'),'PASS')).toBe(false)});
 it('checker records result on assigned inspection',()=>{for(const t of ['PASS','HOLD','REJECT','RE_TEST'])expect(transitionOk(C,R('INSPECTION_PENDING'),t as any)).toBe(true);expect(transitionOk(C,R('INSPECTION_PENDING'),'APPROVED')).toBe(false);expect(transitionOk({...C,uid:'c2'},R('INSPECTION_PENDING'),'PASS')).toBe(false);expect(transitionOk(C,R('DRAFT'),'PASS')).toBe(false)});
 it('only assigned manager approves, only from PASS',()=>{expect(transitionOk(M,R('PASS'),'APPROVED')).toBe(true);expect(transitionOk(M,R('HOLD'),'APPROVED')).toBe(false);expect(transitionOk({...M,uid:'m2'},R('PASS'),'APPROVED')).toBe(false)});
 it('manager can send back for re-inspection',()=>expect(transitionOk({...M,uid:'m2'},R('REJECT'),'INSPECTION_PENDING')).toBe(true));
 it('approved is locked for everyone but admin',()=>{expect(nextStatuses(M,R('APPROVED'))).toEqual([]);expect(nextStatuses(C,R('APPROVED'))).toEqual([]);expect(nextStatuses({role:'admin',uid:'x'},R('APPROVED')).length).toBeGreaterThan(0)});
 it('customer / production can do nothing',()=>{for(const role of ['customer','production'])expect(nextStatuses({role,uid:'z'},R('DRAFT'))).toEqual([]);expect(canCreate('customer')).toBe(false);expect(canCreate('qc_checker')).toBe(false);expect(canCreate('qc_assistant')).toBe(true)});
 it('edit scope',()=>{expect(editScope(A,R('DRAFT'))).toBe('details');expect(editScope(A,R('PASS'))).toBe('none');expect(editScope(C,R('INSPECTION_PENDING'))).toBe('remarks');expect(editScope(M,R('PASS'))).toBe('all');expect(editScope(M,R('APPROVED'))).toBe('none');expect(editScope({role:'admin',uid:'x'},R('APPROVED'))).toBe('all')});
 it('dates and messages',()=>{expect(isoOffset(1,new Date(2026,8,18,12))).toBe('2026-09-17');expect(isoOffset(0,new Date(2026,8,18,12))).toBe('2026-09-18');expect(emptyReportsMessage('Pepsi','2026-09-18','2026-09-18',true)).toBe('No Pepsi QC reports found for the selected date.');expect(ILABEL('RE_TEST')).toBe('RE-TEST');expect(ILABEL('INSPECTION_PENDING')).toBe('INSPECTION PENDING')})});
