import {useEffect,useMemo,useState,FormEvent} from 'react';import {Link,NavLink,Navigate,useNavigate,useParams,useSearchParams} from 'react-router-dom';
import {sb,useAuth} from './lib';import {fmtStamp} from './monitor';import {IStatus,ISTATUS,ILABEL,IMETA,transitionOk,nextStatuses,ACTION_LABEL,editScope,canCreate,isoLocal,Rep} from './workflow';
export const StatusBadge=({s}:{s:string})=>{const m=IMETA[s as IStatus];return <span className="ib" style={{background:m?.color}}>{m?.icon} {ILABEL(s)}</span>};
const TABS:[string,string][]=[['/app/reports','All Reports'],['/app/reports/new','New Inspection'],['/app/reports?status=INSPECTION_PENDING','Inspection Pending'],['/app/reports?status=HOLD','Hold'],['/app/reports?status=RE_TEST','Re-Test'],['/app/reports?status=APPROVED','Approved']];
function ReportsNav(){const {profile}=useAuth();const loc=window.location;const cur=loc.pathname+loc.search;
 return <div className="tabs rtabs">{TABS.filter(([p])=>p!=='/app/reports/new'||canCreate(profile?.role)).map(([p,l])=><Link key={p} to={p} className={cur===p||(p==='/app/reports'&&cur==='/app/reports')?'on':''}>{l}</Link>)}</div>}
const PAGE=25;
export function ReportsList(){const [sp]=useSearchParams();const status=sp.get('status')||'';const [f,setF]=useState<any>({});const [page,setPage]=useState(0);const [rows,setRows]=useState<any[]>([]);const [total,setTotal]=useState(0);const [err,setErr]=useState('');const [loaded,setLoaded]=useState(false);
 const [deps,setDeps]=useState<any[]>([]);const [procs,setProcs]=useState<any[]>([]);const [machs,setMachs]=useState<any[]>([]);const [custs,setCusts]=useState<any[]>([]);
 useEffect(()=>{sb.from('departments').select('id,name').order('name').then(r=>setDeps(r.data||[]));sb.from('processes').select('id,name,department_id').order('sort').then(r=>setProcs(r.data||[]));sb.from('machines').select('id,name,department_id,process_id').order('name').then(r=>setMachs(r.data||[]));sb.from('customers').select('id,name').order('name').then(r=>setCusts(r.data||[]))},[]);
 const set=(p:any)=>{setF((o:any)=>({...o,...p}));setPage(0)};
 useEffect(()=>{setPage(0)},[status]);
 useEffect(()=>{let q=sb.from('inspections').select('id,report_id,status,product,batch,inspection_date,inspection_time,department:departments(name),process:processes(name),machine:machines(name),customer:customers(name)',{count:'exact'}).order('inspection_date',{ascending:false}).order('created_at',{ascending:false}).range(page*PAGE,page*PAGE+PAGE-1);
  if(status)q=q.eq('status',status);if(f.st)q=q.eq('status',f.st);if(f.rid?.trim())q=q.ilike('report_id',`%${f.rid.trim()}%`);if(f.prod?.trim())q=q.ilike('product',`%${f.prod.trim()}%`);if(f.batch?.trim())q=q.ilike('batch',`%${f.batch.trim()}%`);
  if(f.from)q=q.gte('inspection_date',f.from);if(f.to)q=q.lte('inspection_date',f.to);if(f.dep)q=q.eq('department_id',f.dep);if(f.proc)q=q.eq('process_id',f.proc);if(f.mach)q=q.eq('machine_id',f.mach);if(f.cust)q=q.eq('customer_id',f.cust);
  q.then(r=>{if(r.error)setErr(r.error.message);else{setErr('');setRows(r.data||[]);setTotal(r.count||0)}setLoaded(true)})},[f,page,status]);
 const filtered=Object.values(f).some(Boolean)||!!status;
 return <div><h2>QC REPORTS</h2><ReportsNav/>
 <div className="card filt"><input placeholder="Report ID" onChange={e=>set({rid:e.target.value})}/><input placeholder="Product / Material" onChange={e=>set({prod:e.target.value})}/><input placeholder="Batch / Lot No." onChange={e=>set({batch:e.target.value})}/>
 <label>From<input type="date" onChange={e=>set({from:e.target.value})}/></label><label>To<input type="date" onChange={e=>set({to:e.target.value})}/></label>
 <select onChange={e=>set({dep:e.target.value,proc:'',mach:''})}><option value="">Department</option>{deps.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select>
 <select value={f.proc||''} onChange={e=>set({proc:e.target.value,mach:''})}><option value="">Process / Section</option>{procs.filter(p=>!f.dep||p.department_id===f.dep).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select>
 <select value={f.mach||''} onChange={e=>set({mach:e.target.value})}><option value="">Machine</option>{machs.filter(m=>(!f.dep||m.department_id===f.dep)&&(!f.proc||m.process_id===f.proc)).map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select>
 <select onChange={e=>set({cust:e.target.value})}><option value="">Customer</option>{custs.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select>
 {!status&&<select onChange={e=>set({st:e.target.value})}><option value="">Any status</option>{ISTATUS.map(s=><option key={s} value={s}>{ILABEL(s)}</option>)}</select>}</div>
 {err&&<p className="err">{err}</p>}
 {loaded&&rows.length===0?<p className="mut">{status==='INSPECTION_PENDING'&&!Object.values(f).some(Boolean)?'No pending inspections.':filtered?'No QC inspection reports match the selected filters.':'No QC inspection reports available.'}</p>:
 <div className="card"><table><thead><tr><th>Report ID</th><th>Status</th><th>Department</th><th>Process</th><th>Machine</th><th>Customer</th><th>Product</th><th>Batch</th><th>Date</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><Link to={`/app/reports/${r.report_id}`}>{r.report_id}</Link></td><td><StatusBadge s={r.status}/></td><td>{r.department?.name}</td><td>{r.process?.name||'—'}</td><td>{r.machine?.name}</td><td>{r.customer?.name}</td><td>{r.product}</td><td>{r.batch}</td><td>{r.inspection_date} {String(r.inspection_time).slice(0,5)}</td></tr>)}</tbody></table>
 <p className="mut">{total} report(s) · page {page+1} of {Math.max(1,Math.ceil(total/PAGE))} <button disabled={page===0} onClick={()=>setPage(page-1)}>‹ Prev</button> <button disabled={(page+1)*PAGE>=total} onClick={()=>setPage(page+1)}>Next ›</button></p></div>}</div>}

export function NewInspection(){const nav=useNavigate();const {profile}=useAuth();const [step,setStep]=useState(1);const [err,setErr]=useState('');const [busy,setBusy]=useState(false);
 const now=new Date();const [f,setF]=useState<any>({date:isoLocal(now),time:`${String(now.getHours()).padStart(2,'0')}:${String(now.getMinutes()).padStart(2,'0')}`,a:profile?.role==='qc_assistant'?profile.id:''});
 const [deps,setDeps]=useState<any[]>([]);const [procs,setProcs]=useState<any[]>([]);const [machs,setMachs]=useState<any[]>([]);const [custs,setCusts]=useState<any[]>([]);const [users,setUsers]=useState<any[]>([]);const [hist,setHist]=useState<any[]>([]);
 const set=(p:any)=>setF((o:any)=>({...o,...p}));
 useEffect(()=>{sb.from('departments').select('id,name,code').eq('active',true).order('name').then(r=>setDeps(r.data||[]));sb.from('profiles').select('id,full_name,role').eq('active',true).in('role',['qc_assistant','qc_checker','qa_qc_manager']).order('full_name').then(r=>setUsers(r.data||[]));sb.from('inspections').select('product,batch').limit(300).then(r=>setHist(r.data||[]))},[]);
 useEffect(()=>{if(!f.dep){setProcs([]);setMachs([]);setCusts([]);return}
  sb.from('processes').select('id,name').eq('department_id',f.dep).eq('active',true).order('sort').then(r=>setProcs(r.data||[]));
  sb.from('machines').select('id,name,process_id').eq('department_id',f.dep).eq('active',true).order('name').then(r=>setMachs(r.data||[]));
  sb.from('customer_department_access').select('customers(id,name,active)').eq('department_id',f.dep).eq('active',true).then(r=>setCusts(((r.data||[]) as any[]).map(x=>x.customers).filter((c:any)=>c?.active)))},[f.dep]);
 const hasProcs=procs.length>0;const list=machs.filter(m=>hasProcs?m.process_id===f.proc:m.process_id===null);
 const valid=[true,!!f.dep&&(!hasProcs||!!f.proc)&&!!f.mach,!!f.cust&&!!f.product?.trim()&&!!f.batch?.trim(),!!f.date&&!!f.time,!!f.a&&!!f.c&&!!f.q][step];
 const hint=['','Select department, process / section and machine.','Select a customer and enter Product / Material and Batch / Lot No.','Inspection date and time are required.','Assign a QC Assistant, QC Checker and QA/QC Manager.'][step];
 const name=(l:any[],id:string)=>l.find(x=>x.id===id)?.name||l.find(x=>x.id===id)?.full_name||'—';const U=(r:string)=>users.filter(u=>u.role===r);
 const submit=async()=>{setBusy(true);setErr('');const {data,error}=await sb.from('inspections').insert({department_id:f.dep,process_id:hasProcs?f.proc:null,machine_id:f.mach,customer_id:f.cust,product:f.product.trim(),batch:f.batch.trim(),inspection_date:f.date,inspection_time:f.time,general_remarks:f.rem?.trim()||null,qc_assistant_id:f.a,qc_checker_id:f.c,qa_manager_id:f.q}).select('report_id').single();setBusy(false);if(error)setErr(error.message);else nav(`/app/reports/${data!.report_id}`)};
 if(!canCreate(profile?.role))return <Navigate to="/app/reports" replace/>;
 const L=['Department → Process → Machine','Customer · Product · Batch','Inspection details','Assign'];
 return <div><h2>QC REPORTS</h2><ReportsNav/><div className="card"><h3 style={{marginTop:0}}>New Inspection</h3><div className="steps">{L.map((l,i)=><span key={l} className={step===i+1?'on':step>i+1?'done':''}>{i+1}. {l}</span>)}</div>
 {step===1&&<div className="addf"><select value={f.dep||''} onChange={e=>set({dep:e.target.value,proc:'',mach:'',cust:''})}><option value="">Department</option>{deps.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select>
  {hasProcs&&<select value={f.proc||''} onChange={e=>set({proc:e.target.value,mach:''})}><option value="">Process / Section</option>{procs.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select>}
  <select value={f.mach||''} disabled={!f.dep||(hasProcs&&!f.proc)} onChange={e=>set({mach:e.target.value})}><option value="">Machine</option>{list.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select>{f.dep&&!hasProcs&&<small className="mut">This department has machines directly.</small>}</div>}
 {step===2&&<div className="addf"><select value={f.cust||''} onChange={e=>set({cust:e.target.value})}><option value="">Customer (authorized for this department)</option>{custs.map(c=>c&&<option key={c.id} value={c.id}>{c.name}</option>)}</select>{custs.length===0&&<small className="mut">No customer is authorized for this department yet (Admin → Customer Access).</small>}
  <input list="prods" placeholder="Product / Material" value={f.product||''} onChange={e=>set({product:e.target.value})}/><datalist id="prods">{[...new Set(hist.map(h=>h.product).filter(Boolean))].map(p=><option key={p} value={p}/>)}</datalist>
  <input list="bats" placeholder="Batch / Lot No." value={f.batch||''} onChange={e=>set({batch:e.target.value})}/><datalist id="bats">{[...new Set(hist.map(h=>h.batch).filter(Boolean))].map(p=><option key={p} value={p}/>)}</datalist></div>}
 {step===3&&<div className="addf"><label>Inspection date<input type="date" value={f.date} onChange={e=>set({date:e.target.value})}/></label><label>Inspection time<input type="time" value={f.time} onChange={e=>set({time:e.target.value})}/></label><textarea rows={4} placeholder="General remarks (internal)" value={f.rem||''} onChange={e=>set({rem:e.target.value})}/></div>}
 {step===4&&<div className="addf"><select value={f.a||''} onChange={e=>set({a:e.target.value})}><option value="">QC Assistant</option>{U('qc_assistant').map(u=><option key={u.id} value={u.id}>{u.full_name}</option>)}</select>
  <select value={f.c||''} onChange={e=>set({c:e.target.value})}><option value="">QC Checker</option>{U('qc_checker').map(u=><option key={u.id} value={u.id}>{u.full_name}</option>)}</select>
  <select value={f.q||''} onChange={e=>set({q:e.target.value})}><option value="">QA/QC Manager</option>{U('qa_qc_manager').map(u=><option key={u.id} value={u.id}>{u.full_name}</option>)}</select>
  <div className="card"><b>Summary</b><br/>{deps.find(d=>d.id===f.dep)?.name} › {hasProcs?name(procs,f.proc):'machines'} › {name(machs,f.mach)}<br/>{name(custs.filter(Boolean),f.cust)} · {f.product} · {f.batch}<br/>{f.date} {f.time}</div></div>}
 <p>{step>1&&<button onClick={()=>setStep(step-1)}>Back</button>} {step<4?<button disabled={!valid} onClick={()=>setStep(step+1)}>Next</button>:<button disabled={!valid||busy} onClick={submit}>{busy?'Creating…':'Create inspection'}</button>} {!valid&&<span className="mut">{hint}</span>}</p>{err&&<p className="err">{err}</p>}</div></div>}

export function ReportDetail(){const {rid}=useParams();const nav=useNavigate();const {profile}=useAuth();const [r,setR]=useState<any>(null);const [missing,setMissing]=useState(false);const [err,setErr]=useState('');const [edit,setEdit]=useState(false);const [e,setE]=useState<any>({});const [users,setUsers]=useState<any[]>([]);const [log,setLog]=useState<any[]>([]);const [names,setNames]=useState<Record<string,string>>({});
 const load=()=>{sb.from('inspections').select('*,department:departments(name),process:processes(name),machine:machines(name),customer:customers(name),assistant:profiles!qc_assistant_id(full_name),checker:profiles!qc_checker_id(full_name),manager:profiles!qa_manager_id(full_name)').eq('report_id',rid!).maybeSingle().then(x=>{if(!x.data)setMissing(true);else{setR(x.data);setE(x.data)}});
  sb.from('audit_logs').select('action,created_at,user_id,details').eq('entity_type','inspection').eq('entity_id',rid!).order('created_at',{ascending:false}).then(x=>setLog(x.data||[]))};
 useEffect(()=>{load();sb.from('profiles').select('id,full_name,role').eq('active',true).in('role',['qc_assistant','qc_checker','qa_qc_manager']).then(x=>setUsers(x.data||[]));sb.from('profiles').select('id,full_name').then(x=>setNames(Object.fromEntries((x.data||[]).map((p:any)=>[p.id,p.full_name]))))},[rid]);
 const me={role:profile!.role,uid:profile!.id};const rep=r as Rep|null;
 const scope=useMemo(()=>r?editScope(me,r):'none',[r]);const acts=useMemo(()=>r?nextStatuses(me,r):[],[r]);
 if(missing)return <div className="card"><h2>Report not found</h2><p>This report does not exist or you do not have access to it.</p><Link to="/app/reports">← QC Reports</Link></div>;if(!r)return <p>Loading…</p>;
 const go=async(s:IStatus)=>{if((s==='APPROVED'||s==='REJECT')&&!confirm(`${ILABEL(s)} this report?`))return;const {error}=await sb.from('inspections').update({status:s}).eq('id',r.id);setErr(error?.message||'');load()};
 const save=async()=>{const p:any={};if(!e.batch?.trim()||!e.product?.trim())return setErr('Product / Material and Batch / Lot No. are required');
  if(scope==='remarks')p.general_remarks=e.general_remarks;else{Object.assign(p,{product:e.product.trim(),batch:e.batch.trim(),inspection_date:e.inspection_date,inspection_time:e.inspection_time,general_remarks:e.general_remarks});if(scope==='all'&&profile!.role!=='admin'||scope==='all'&&profile!.role==='admin')Object.assign(p,{qc_assistant_id:e.qc_assistant_id,qc_checker_id:e.qc_checker_id,qa_manager_id:e.qa_manager_id})}
  const {error}=await sb.from('inspections').update(p).eq('id',r.id);setErr(error?.message||'');if(!error)setEdit(false);load()};
 const del=async()=>{if(!confirm('Delete this draft report?'))return;const {error}=await sb.from('inspections').delete().eq('id',r.id);if(error)setErr(error.message);else nav('/app/reports')};
 const row=(k:string,v:any)=><tr><th>{k}</th><td>{v||'—'}</td></tr>;const U=(ro:string,k:string)=><select value={e[k]||''} onChange={x=>setE({...e,[k]:x.target.value})}>{users.filter(u=>u.role===ro).map(u=><option key={u.id} value={u.id}>{u.full_name}</option>)}</select>;
 const flow=['DRAFT','INSPECTION_PENDING','QC INSPECTION','PASS / HOLD / REJECT / RE-TEST','APPROVED'];const idx=r.status==='DRAFT'?0:r.status==='INSPECTION_PENDING'?2:r.status==='APPROVED'?4:3;
 return <div><div className="card"><Link to="/app/reports">← QC Reports</Link><h2 style={{margin:'6px 0'}}>REPORT ID: {r.report_id} <StatusBadge s={r.status}/></h2><div className="steps">{flow.map((s,i)=><span key={s} className={i===idx?'on':i<idx?'done':''}>{s}</span>)}</div></div>
 <div className="card"><table><tbody>{row('Department',r.department?.name)}{row('Process / Section',r.process?.name)}{row('Machine',r.machine?.name)}{row('Customer',r.customer?.name)}
 {edit?<><tr><th>Product / Material</th><td><input disabled={scope==='remarks'} value={e.product||''} onChange={x=>setE({...e,product:x.target.value})}/></td></tr><tr><th>Batch / Lot No.</th><td><input disabled={scope==='remarks'} value={e.batch||''} onChange={x=>setE({...e,batch:x.target.value})}/></td></tr>
  <tr><th>Inspection Date / Time</th><td><input type="date" disabled={scope==='remarks'} value={e.inspection_date} onChange={x=>setE({...e,inspection_date:x.target.value})}/><input type="time" disabled={scope==='remarks'} value={String(e.inspection_time).slice(0,5)} onChange={x=>setE({...e,inspection_time:x.target.value})}/></td></tr>
  {scope==='all'&&<tr><th>Assigned</th><td>{U('qc_assistant','qc_assistant_id')}{U('qc_checker','qc_checker_id')}{U('qa_qc_manager','qa_manager_id')}</td></tr>}<tr><th>General Remarks</th><td><textarea rows={3} value={e.general_remarks||''} onChange={x=>setE({...e,general_remarks:x.target.value})}/></td></tr></>
 :<>{row('Product / Material',r.product)}{row('Batch / Lot No.',r.batch)}{row('Inspection Date',r.inspection_date)}{row('Inspection Time',String(r.inspection_time).slice(0,5))}{row('QC Assistant',r.assistant?.full_name)}{row('QC Checker',r.checker?.full_name)}{row('QA/QC Manager',r.manager?.full_name)}{row('General Remarks',r.general_remarks)}</>}
 {row('Created At',fmtStamp(r.created_at))}{row('Updated At',fmtStamp(r.updated_at))}</tbody></table>
 <div className="acts">{scope!=='none'&&!edit&&<button onClick={()=>setEdit(true)}>Edit</button>}{edit&&<><button onClick={save}>Save</button><button onClick={()=>{setEdit(false);setE(r);setErr('')}}>Cancel</button></>}
 {!edit&&acts.map(s=><button key={s} className={`a-${s}`} onClick={()=>go(s)}>{ACTION_LABEL(r.status,s)}</button>)}{profile!.role==='admin'&&r.status==='DRAFT'&&<button className="a-REJECT" onClick={del}>Delete draft</button>}</div>{err&&<p className="err">{err}</p>}</div>
 <div className="card"><h3 style={{marginTop:0}}>QC INSPECTION PARAMETERS</h3><p className="mut">QC parameters will be configured after the original QC report sheets are provided.</p></div>
 {log.length>0&&<div className="card"><h3 style={{marginTop:0}}>History</h3>{log.map((l,i)=><div key={i} className="hist"><b>{l.action.replace(/_/g,' ')}</b>{l.details?.from?` · ${ILABEL(l.details.from)} → ${ILABEL(l.details.to)}`:''}{l.details?.changed_fields?` · ${l.details.changed_fields.join(', ')}`:''}<span className="mut"> — {names[l.user_id]||'—'} · {fmtStamp(l.created_at)}</span></div>)}</div>}</div>}
void transitionOk;void NavLink;void useState;void({} as FormEvent);
